/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../models/home.gltf"););
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0, -0.25, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group position={[0, 0, 47.31]} scale={2}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Scene014.geometry}
            material={materials.TheMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Scene014_1.geometry}
            material={materials.Glass}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/home.gltf");
